services:
  - type: web
    name: CentraC
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: centrac-data
      mountPath: /data
      sizeGB: 1
